version: '3.7'
services:
  db:
    image: mariadb:10.6.21
    container_name: cacti_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cacti
      MYSQL_USER: cacti
      MYSQL_PASSWORD: cacti_password
      MYSQL_INITDB_SKIP_TZINFO: 0
    volumes:
      - ./db:/var/lib/mysql
  cacti:
#    image:
    build: .
    container_name: cacti_app
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=cacti
      - DB_USER=cacti
      - DB_PASSWORD=cacti_password
      - TZ=Europe/Berlin
    depends_on:
      - db
    volumes:
    #  - ./cacti_plugins:/var/www/htnl/plugins
    #  - ./cacti_log:/var/www/htnl/log
