services:
  db:
    image: mariadb:10.6.21
    container_name: cacti_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cacti
      MYSQL_USER: cacti
      MYSQL_PASSWORD: changeme
      MYSQL_INITDB_SKIP_TZINFO: 0
      TZ: Europe/Berlin
    volumes:
      - ./cacti_db:/var/lib/mysql
      - ./maria-config:/etc/mysql/mariadb.conf.d
  cacti:
#    image: itsegner/cacti:latest
#    image: itsegner/cacti-develop:latest
    build: .
    container_name: cacti_app
    restart: unless-stopped
    ports:
      - "7070:80"
    environment:
      CACTI_DB_HOST: "db"
      CACTI_DB_NAME: "cacti"
      CACTI_DB_USER: "cacti"
      CACTI_DB_PASS: "changeme"
      TZ: Europe/Berlin
    depends_on:
      - db
    volumes:
      - ./cacti_rra:/var/www/html/cacti/rra
      - ./cacti_plugins:/var/www/html/cacti/plugins
      - ./cacti_log:/var/www/html/cacti/log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
