services:
  db:
    image: mariadb:10.6.21
    container_name: cacti_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cacti
      MYSQL_USER: cacti
      MYSQL_PASSWORD: changeme
      MYSQL_INITDB_SKIP_TZINFO: 0
      TZ: Europe/Berlin
    volumes:
      - ./cacti_db:/var/lib/mysql
      - ./maria-config:/etc/mysql/mariadb.conf.d
  cacti:
#    image:
    build: .
    container_name: cacti_app
    ports:
      - "7070:80"
    environment:
      CACTI_DB_HOST: "db"
      CACTI_DB_NAME: "cacti"
      CACTI_DB_USER: "cacti"
      CACTI_DB_PASS: "changeme"
      TZ: Europe/Berlin
    depends_on:
      - db
    volumes:
      - ./cacti_rra:/var/www/htnl/rra
      - ./cacti_plugins:/var/www/htnl/plugins
      - ./cacti_log:/var/www/htnl/log
